version: '3.8'

services:
  tracker:
    container_name: torrent-tracker
    image: chronicle-opentracker:latest
    user: root
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    volumes:
      - ./data/tracker:/data

  transmission:
    container_name: chronicle-transmission
    image: linuxserver/transmission:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ./data/transmission/config:/config
      - ./data/downloads:/downloads
      - ./data/watch:/watch
    networks:
      - chronicle-network
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"

networks:
  chronicle-network:
    name: chronicle-network 