services:
  localstack:
    image: localstack/localstack:latest
    privileged: true
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb,lambda,apigateway,logs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DATA_DIR=/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_FLAGS=--user root:root -v /var/run/docker.sock:/var/run/docker.sock:rw
    volumes:
      - localstack_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  localstack_data:
